name: QA Automation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      BOOKER_BASE_URL: https://restful-booker.herokuapp.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug BOOKER_BASE_URL
        run: echo "BOOKER_BASE_URL=$BOOKER_BASE_URL"

      - name: Run API tests
        run: |
          pytest api/tests --html=reports/api_report.html --self-contained-html

      - name: Run UI tests
        run: |
          pytest ui/tests --html=reports/ui_report.html --self-contained-html

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/**
